[project]
name = "scenario-generator-tt"
version = "0.1.0"
description = "Traffic scenario generator backend (Flask)"
requires-python = ">=3.9"
dependencies = [
  "Flask>=2.2,<4",
  "Flask-Cors>=4.0.0,<5",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta" 